apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: url-shortener-deployment
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: url-shortener-app
          image: "docker.io/notmde/url-shortener:v2"
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URI
              value: "redis://redis-service:6379"
            - name: APP_PORT
              value: "3000"
            - name: DEV_FLAG
              value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: app-port