#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: url-shortener-deployment
#spec:
#  replicas: 2
#  template:
#    spec:
#      containers:
#        - name: url-shortener-app
#          image: "docker.io/notmde/url-shortener:v2"
#          ports:
#            - containerPort: 3000

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: url-shortener-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: url-shortener-app
          image: "docker.io/notmde/url-shortener:v2"
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URI
              value: "redis://redis-service:6379"
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: app-port