apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: traefik-service
spec:
  weighted:
    services:
      - name: stable-rollout
        port: 80
      - name: canary-rollout
        port: 80

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: url-shortener-deployment
  namespace: default
  labels:
    app: url-shortener
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener-app
          image: "docker.io/notmde/url-shortener:v2"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URI
              value: "redis://redis-service:6379"
            - name: APP_PORT
              value: "3000"
            - name: DEV_FLAG
              value: "1"

  strategy:
    canary:
      canaryService: canary-rollout
      stableService: stable-rollout

      canaryMetadata:
        labels:
          role: canary
        annotations:
          role: canary
      stableMetadata:
        labels:
          role: stable
        annotations:
          role: stable

      trafficRouting:
        traefik:
          weightedTraefikServiceName: traefik-service

      steps:
        - setWeight: 30
        - pause: { }
        - setWeight: 40
        - pause: { duration: 10 }
        - setWeight: 60
        - pause: { duration: 10 }
        - setWeight: 80
        - pause: { duration: 10 }