apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: service-url
  metrics:
    - name: success-rate
      interval: 10s
      successCondition: response.code == 200
      failureCondition: response.code != 200
      failureLimit: 3
      provider:
        web:
          url: "{{args.service-url}}"
          timeout: 5s