apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: canary-rollout
spec:
  type: ClusterIP
  selector:
    app: traefik
  ports:
    - port: 80
      targetPort: canary-rollout

---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: stable-rollout
spec:
  type: ClusterIP
  selector:
    app: traefik
  ports:
    - port: 80
      targetPort: stable-rollout

---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: traefik-service
spec:
  weighted:
    services:
      - name: stable-rollout
        port: 80
      - name: canary-rollout
        port: 80

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: url-shortener-deployment
  namespace: default
  labels:
    app: url-shortener
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener-app
          imagePullPolicy: Always
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

  strategy:
    canary:
      canaryService: canary-rollout
      stableService: stable-rollout
      trafficRouting:
        traefik:
          weightedTraefikServiceName: traefik-web-service
      steps:
        - setWeight: 30
        - pause: { }
        - setWeight: 40
        - pause: { duration: 10 }
        - setWeight: 60
        - pause: { duration: 10 }
        - setWeight: 80
        - pause: { duration: 10 }
      analysis:
        templates:
          - templateName: success-rate
            startingStep: 2
            args:
              - name: service-url
                value: "traefik-web-service.traefik.svc.cluster.local"