apiVersion: v1
kind: Service
metadata:
  name: canary-rollout
  namespace: default
spec:
  selector:
    app: url-shortener
  ports:
    - name: app-port
      port: 80
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: stable-rollout
  namespace: default
spec:
  selector:
    app: url-shortener
  ports:
    - name: app-port
      port: 80
      targetPort: 3000