apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  selector:
    app: url-shortener
  ports:
  - port: 80
    targetPort: 8080
    name: app-port
  type: ClusterIP